services:
    eas_listener:
        build: .
        container_name: eas_listener
        restart: unless-stopped
        volumes:
            - ./data:/data
            - ./apprise.yml:/app/apprise.yml
            - ./web_server:/var/www/html
            - ./leadin.mp3:/app/leadin.mp3
            - ./leadout.mp3:/app/leadout.mp3
            - ./config.json:/app/config.json
        env_file:
            - .env
        ports:
            - "${WEB_SERVER_PORT}:80"
            - "${MONITORING_BIND_PORT}:${MONITORING_BIND_PORT}"
