services:
    eas_listener:
        image: ghcr.io/wagwan-piffting-blud/eas-listener:latest
        container_name: eas_listener
        restart: unless-stopped
        volumes:
            - ./data:/data
            - ./apprise.yml:/app/apprise.yml
            # - ./leadin.mp3:/app/leadin.mp3         # Include if you have lead-in audio and want to use it when relaying
            # - ./leadout.mp3:/app/leadout.mp3       # Include if you have lead-out audio and want to use it when relaying
            - ./config.json:/app/config.json
        env_file:
            - .env
        ports:
            - "${WEB_SERVER_PORT}:80"
            - "${MONITORING_BIND_PORT}:${MONITORING_BIND_PORT}"
